spring.application.name=movies_searcher
server.port= 8092
## Conexion a la base de datos


# Oracle settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:Db_prueba
spring.datasource.username=dany
spring.datasource.password=dany
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

## Evitar que se cree el esquema de bd
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql=true

#Desactivar tomcat
#spring.main.web-application-type=none

#Desactivar jta
#spring.jta.enabled = false




